require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProductSizesController do

  # This should return the minimal set of attributes required to create a valid
  # ProductSize. As you add validations to ProductSize, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductSizesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all product_sizes as @product_sizes" do
      product_size = ProductSize.create! valid_attributes
      get :index, {}, valid_session
      assigns(:product_sizes).should eq([product_size])
    end
  end

  describe "GET show" do
    it "assigns the requested product_size as @product_size" do
      product_size = ProductSize.create! valid_attributes
      get :show, {:id => product_size.to_param}, valid_session
      assigns(:product_size).should eq(product_size)
    end
  end

  describe "GET new" do
    it "assigns a new product_size as @product_size" do
      get :new, {}, valid_session
      assigns(:product_size).should be_a_new(ProductSize)
    end
  end

  describe "GET edit" do
    it "assigns the requested product_size as @product_size" do
      product_size = ProductSize.create! valid_attributes
      get :edit, {:id => product_size.to_param}, valid_session
      assigns(:product_size).should eq(product_size)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProductSize" do
        expect {
          post :create, {:product_size => valid_attributes}, valid_session
        }.to change(ProductSize, :count).by(1)
      end

      it "assigns a newly created product_size as @product_size" do
        post :create, {:product_size => valid_attributes}, valid_session
        assigns(:product_size).should be_a(ProductSize)
        assigns(:product_size).should be_persisted
      end

      it "redirects to the created product_size" do
        post :create, {:product_size => valid_attributes}, valid_session
        response.should redirect_to(ProductSize.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved product_size as @product_size" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductSize.any_instance.stub(:save).and_return(false)
        post :create, {:product_size => {}}, valid_session
        assigns(:product_size).should be_a_new(ProductSize)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductSize.any_instance.stub(:save).and_return(false)
        post :create, {:product_size => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested product_size" do
        product_size = ProductSize.create! valid_attributes
        # Assuming there are no other product_sizes in the database, this
        # specifies that the ProductSize created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProductSize.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => product_size.to_param, :product_size => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested product_size as @product_size" do
        product_size = ProductSize.create! valid_attributes
        put :update, {:id => product_size.to_param, :product_size => valid_attributes}, valid_session
        assigns(:product_size).should eq(product_size)
      end

      it "redirects to the product_size" do
        product_size = ProductSize.create! valid_attributes
        put :update, {:id => product_size.to_param, :product_size => valid_attributes}, valid_session
        response.should redirect_to(product_size)
      end
    end

    describe "with invalid params" do
      it "assigns the product_size as @product_size" do
        product_size = ProductSize.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductSize.any_instance.stub(:save).and_return(false)
        put :update, {:id => product_size.to_param, :product_size => {}}, valid_session
        assigns(:product_size).should eq(product_size)
      end

      it "re-renders the 'edit' template" do
        product_size = ProductSize.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductSize.any_instance.stub(:save).and_return(false)
        put :update, {:id => product_size.to_param, :product_size => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested product_size" do
      product_size = ProductSize.create! valid_attributes
      expect {
        delete :destroy, {:id => product_size.to_param}, valid_session
      }.to change(ProductSize, :count).by(-1)
    end

    it "redirects to the product_sizes list" do
      product_size = ProductSize.create! valid_attributes
      delete :destroy, {:id => product_size.to_param}, valid_session
      response.should redirect_to(product_sizes_url)
    end
  end

end
